/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Graph: typeof import('./src/components/graph.vue')['default']
    Visualizer: typeof import('./src/components/Visualizer.vue')['default']
  }
}
